### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by rdoursenaud**

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Thanks! The continue move will make this a breaking change. @dherrada, please merge this before you do a new major release and note that the continue imports will have to be changed.

**Comment by rdoursenaud** [comment]
Please don’t merge.

`continue` is a [reserved Python keyword](https://docs.python.org/3/reference/lexical_analysis.html#keywords) and my renaming may cause issues!

Should I revert to the previous naming (which prevented the documentation from properly building) or should I use `continue_` to make it more in line with the other classes?

**Comment by rdoursenaud** [comment]
OK, I’ve found what was preventing the docs from building.

Even though I’ think `continue_` would have been a better name, I’ve settled for not breaking the API and keeping the original `midi_continue` naming.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
