### PR TITLE
Add MIDI Time Code Quarter Frame message support

### PR DESCRIPTION
**Pull request by rdoursenaud**
I’m working on implementing an MTC display using a MatrixPortal Starter Kit.
MTC full frame message are Global SySex and already covered by the System Exclusive message type.
Quarter Frame are their own message type and wasn’t implemented.
Here’s a tentative implementation.

Edit: Sorry for the force pushes, I cleaned up a bit of crust.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Looks good to me! Thank you!

**Comment by tannewt** [comment]
Looks like pylint has a suggestion. I'd suggest installing pre-commit locally: https://learn.adafruit.com/improve-your-code-with-pylint/check-your-code-with-pre-commit

**Comment by rdoursenaud** [comment]
Thanks. Here’s a version with the offending variable renamed.

**Comment by jepler** [comment]
Thanks!  The remaining problem noticed by pylint existed before your changes and we'll address it at #39.

**Pull request merged**
